name: demo

proxy:
  app:
    - cypress.demo.lndo.site

services:
  app:
    type: php:8.0
    via: apache
    webroot: public
    xdebug: true
    build:
      - composer self-update
      - composer install
